version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchlist_app
    restart: always
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/watchlist?schema=public
      - JWT_SECRET=ganti_dengan_kode_rahasia_anda_disini
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma db push --skip-generate && node server.js"

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: watchlist_scraper
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/watchlist?schema=public
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: watchlist_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watchlist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d watchlist"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
