services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchlist_app
    restart: always
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/watchlist?schema=public
      - JWT_SECRET=ganti_dengan_kode_rahasia_anda_disini
      - NODE_OPTIONS=--max-old-space-size=896
      - DISABLE_APP_WORKER=true
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "node ./node_modules/prisma/build/index.js db push --skip-generate && node server.js"
    mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - watchlist_net

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: watchlist_scraper
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/watchlist?schema=public
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - TZ=Asia/Jakarta
    depends_on:
      db:
        condition: service_healthy
    shm_size: "256m"
    mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - watchlist_net

  db:
    image: postgres:15-alpine
    container_name: watchlist_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watchlist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d watchlist"]
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 256m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - watchlist_net

volumes:
  pgdata:

networks:
  watchlist_net:
    driver: bridge
